using BlockCahin_Invoice.Services;
using BlockChain_Invoice.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Threading.Tasks;

namespace BlockCahin_Invoice.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class InvoiceController : ControllerBase
    {
        private readonly EthereumService _ethereumService;

        public InvoiceController(EthereumService ethereumService)
        {
            _ethereumService = ethereumService;
        }

        [HttpPost]
        public async Task<IActionResult> CreateInvoice(string id, string customerName, int amount)
        {
            string jsonString = @"
            {
  ""SaleInvoiceID"": 25621,
  ""DistributionID"": 28,
  ""InvoiceNumber"": null,
  ""InvoiceCode"": ""AM-INV92"",
  ""InvoiceDate"": ""07/24/2023"",
  ""DeliveryDate"": ""07/25/2023"",
  ""CustomerID"": 6309,
  ""ChannelID"": 8,
  ""OrderBookerID"": 1091,
  ""VanID"": 58,
  ""SalemanID"": 71,
  ""SaleNotes"": """",
  ""CustomersRouteID"": null,
  ""RouteName"": ""Unplaned Route"",
  ""DiscountValue"": 0,
  ""TaxValue"": 68.644,
  ""TotalNetValueWithTax"": 411.5384,
  ""TotalNetValueAfterTO"": 411.5384,
  ""WitholdingTaxRate"": null,
  ""WitholdingTaxValue"": null,
  ""Status"": ""Open"",
  ""ParentSaleInvoiceID"": null,
  ""GINID"": null,
  ""Synchronized"": false,
  ""SynchronizedOn"": null,
  ""SynchronizedBy"": """",
  ""Posted"": false,
  ""PostedOn"": null,
  ""PostedBy"": null,
  ""CreatedOn"": ""2023-07-24T16:00:06.253"",
  ""CreatedBy"": ""admin"",
  ""Deleted"": false,
  ""DeletedOn"": null,
  ""DeletedBy"": """",
  ""ModifiedOn"": null,
  ""ModifiedBy"": """",
  ""Attribute1"": null,
  ""Attribute2"": null,
  ""Attribute3"": null,
  ""Attribute4"": null,
  ""Attribute5"": null,
  ""Attribute6"": null,
  ""Attribute7"": null,
  ""TotalBillDiscount"": 0,
  ""Lattitude"": null,
  ""Longitude"": null,
  ""OrderStartTime"": null,
  ""OrderCompleteTime"": null,
  ""ImagePath"": null,
  ""SyncUniqueKey"": null,
  ""isSpotSale"": false,
  ""CheckPromotion"": false,
  ""RemovedPromotion"": """",
  ""isRedeliver"": false,
  ""ShelfRent"": 0,
  ""CustomerRentalDetailID"": null,
  ""TotalTOValue"": 0,
  ""TotalTOPercentageValue"": 0,
  ""OrderedNetAmount"": 411.5384,
  ""promofromWeb"": null,
  ""ClientRecordID"": null,
  ""Channel"": null,
  ""Customer"": {
    ""CustomerID"": 6309,
    ""DistributionID"": 28,
    ""SubLocalityID"": 1244,
    ""LocalityID"": 7,
    ""ChannelID"": 8,
    ""SubChannelID"": 17,
    ""MainCode"": ""ak-cus374"",
    ""Code"": ""AK-CUS374"",
    ""Barcode"": """",
    ""Name"": ""Al Safa Mart"",
    ""LegalName"": ""Al Safa Mart"",
    ""NTN"": """",
    ""STN"": """",
    ""CNIC"": ""3520275432567"",
    ""Phone"": """",
    ""Mobile"": ""03204501290"",
    ""Email"": """",
    ""CreditDays"": 0,
    ""CreditLimit"": 0,
    ""Active"": true,
    ""Status"": ""Approved"",
    ""SalesTaxStatus"": ""UnRegisterd"",
    ""IncomeTaxStatus"": ""Non Filer"",
    ""ShopProgram"": """",
    ""IsFiler"": null,
    ""CreatedOn"": ""2022-01-08T16:39:11"",
    ""CreatedBy"": ""AKshehriyar"",
    ""ModifiedOn"": ""2023-02-28T15:59:08.32"",
    ""ModifiedBy"": ""SNSZaid"",
    ""Deleted"": null,
    ""DeletedOn"": null,
    ""DeletedBy"": null,
    ""Attribute1"": null,
    ""Attribute2"": null,
    ""Attribute3"": null,
    ""Attribute4"": null,
    ""Attribute5"": null,
    ""Attribute6"": null,
    ""Attribute7"": null,
    ""Lattitude"": ""31.5869431"",
    ""Longitude"": ""74.3353165"",
    ""OwnerName"": ""Ali Zubar"",
    ""Remarks"": ""Stock Available Hy"",
    ""Role"": ""OrderBooker"",
    ""OrderbookerID"": 16,
    ""Address"": ""Chowk Nakhuda Shadbagh"",
    ""Landmark"": ""Shadbagh"",
    ""SyncUniqueKey"": ""10-16-0-1641641951623"",
    ""ImagePath"": ""SND_Pictures/SNSApi/CustomerPending_10-16-0-1641641760545.jpg"",
    ""ImageArray"": null,
    ""Synchronized"": true,
    ""SynchronizedOn"": ""2022-01-08T17:43:25.727"",
    ""SynchronizedBy"": ""AKshehriyar"",
    ""ClientRecordID"": null,
    ""Attribute8"": null,
    ""Attribute9"": null,
    ""Attribute10"": null,
    ""SDCode"": null,
    ""Channel"": null,
    ""Distribution"": null,
    ""Locality"": null,
    ""SubChannel"": null,
    ""SubLocality"": null,
    ""CustomerApprovals"": [],
    ""CustomerAddresses"": [],
    ""CustomerPrinciples"": [],
    ""Assets"": [],
    ""SalesmenRecoveryDetails"": [],
    ""CustomerTags"": []
  },
  ""CustomerRentalDetails"": [],
  ""CustomerRoute"": null,
  ""Distribution"": {
    ""DistributionID"": 28,
    ""DistributionGroupID"": 1,
    ""Code"": ""D025"",
    ""DisplayName"": ""AM"",
    ""LegalName"": ""AM Traders"",
    ""NTN"": ""7943532-6"",
    ""STN"": ""3277876297682"",
    ""Phone"": ""03218443215"",
    ""Fax"": """",
    ""Email"": ""anas_shhd@yahoo.com"",
    ""Active"": true,
    ""Latitude"": ""31.601458"",
    ""Longitude"": ""74.341787"",
    ""IsCompany"": null,
    ""CreatedOn"": ""2023-02-09T15:28:35.437"",
    ""CreatedBy"": ""SNSZaid"",
    ""ModifiedOn"": ""2023-04-11T11:22:49.007"",
    ""ModifiedBy"": ""SNSZaid"",
    ""Deleted"": false,
    ""DeletedOn"": null,
    ""DeletedBy"": """",
    ""Attribute1"": null,
    ""Attribute2"": null,
    ""Attribute3"": null,
    ""Attribute4"": null,
    ""Attribute5"": null,
    ""Attribute6"": null,
    ""Attribute7"": null,
    ""PhotoPath"": ""Demo.jpeg"",
    ""Address"": ""10-Akram park amir road shad bagh lahore"",
    ""OwnerCNIC"": """",
    ""OwnerEmail"": ""anas_shhd@yahoo.com"",
    ""SoldTo"": """",
    ""ShipTo"": """",
    ""OwnerName"": ""Anas Shahid"",
    ""OwnerContactNo"": """",
    ""POCDesignation"": """",
    ""POCName"": """",
    ""POCContactNo"": """",
    ""POCEmail"": """",
    ""Level1ID"": 1,
    ""Level2ID"": 3,
    ""Level3ID"": 3,
    ""ClientRecordID"": null,
    ""SynchronizedOn"": null,
    ""SynchronizedBy"": null,
    ""NestleDistributionID"": null,
    ""DistributionType"": null,
    ""HandlerID"": null,
    ""isUsingSystem"": null,
    ""Level1"": null,
    ""Level2"": null,
    ""Level3"": null,
    ""CompanyDistributions"": [],
    ""DistributionPrinciples"": [],
    ""DistributionAccounts"": [],
    ""Claims"": [],
    ""SalesmenRecoveries"": [],
    ""SurveyUserOrderBookerDetails"": [],
    ""DistributionPrices"": [],
    ""Vans"": []
  },
  ""OrderBooker"": null,
  ""Salesman"": {
    ""SalesmenID"": 71,
    ""DistributionID"": 28,
    ""Code"": ""AMSM"",
    ""Name"": ""AMSM"",
    ""CNIC"": """",
    ""ImagePath"": """",
    ""Status"": true,
    ""CreatedOn"": ""2023-02-13T15:45:10.027"",
    ""CreatedBy"": ""SNSZaid"",
    ""ModifiedOn"": ""2023-06-03T19:02:14.313"",
    ""ModifiedBy"": ""SNSZaid"",
    ""Deleted"": false,
    ""DeletedOn"": null,
    ""DeletedBy"": null,
    ""Attribute1"": null,
    ""Attribute2"": null,
    ""Attribute3"": null,
    ""Attribute4"": null,
    ""Attribute5"": null,
    ""Attribute6"": null,
    ""Attribute7"": null,
    ""UserID"": ""647e842f-b45c-4d52-87e1-fb87665d3b51"",
    ""ClientRecordID"": null,
    ""SynchronizedOn"": null,
    ""SynchronizedBy"": null,
    ""AspNetUser"": null,
    ""Distribution"": null,
    ""GINS"": [],
    ""SaleInvoices"": [],
    ""SalesmenOrderBookers"": [],
    ""VanSalesmen"": [],
    ""CustomerLedgers"": [],
    ""SalesmenRecoveries"": []
  },
  ""Van"": {
    ""VanID"": 58,
    ""DistributionID"": 28,
    ""Code"": ""AM-V2"",
    ""Name"": ""VAN1"",
    ""VehicleTypeID"": null,
    ""RegistrationNumber"": """",
    ""Year"": """",
    ""Make"": """",
    ""Model"": """",
    ""WeightCapacity"": null,
    ""Width"": null,
    ""Length"": null,
    ""Height"": null,
    ""ImagePath"": """",
    ""Status"": true,
    ""CreatedOn"": ""2023-02-15T10:28:49.193"",
    ""CreatedBy"": ""SNSZaid"",
    ""ModifiedOn"": ""2023-06-03T19:44:17.827"",
    ""ModifiedBy"": ""FSNaeem"",
    ""Deleted"": false,
    ""DeletedOn"": null,
    ""DeletedBy"": """",
    ""Attribute1"": null,
    ""Attribute2"": null,
    ""Attribute3"": null,
    ""Attribute4"": null,
    ""Attribute5"": null,
    ""Attribute6"": null,
    ""Attribute7"": null,
    ""ClientRecordID"": null,
    ""SynchronizedOn"": null,
    ""SynchronizedBy"": null,
    ""GINS"": [],
    ""VanSalesmen"": [],
    ""SaleInvoices"": [],
    ""Distribution"": null,
    ""VehicleType"": null
  },
  ""SaleInvoiceDetails"": [
    {
      ""SaleInvoiceDetailID"": 139030,
      ""SaleInvoiceID"": 25621,
      ""ProductID"": 11,
      ""CartonOrdered"": null,
      ""BoxOrdered"": null,
      ""PiecesOrdered"": 2,
      ""CartonDelivered"": null,
      ""BoxDelivered"": null,
      ""PiecesDelivered"": null,
      ""TotalPiecesOrdered"": 2,
      ""TotalPiecesDelivered"": null,
      ""DistributionMarginRate"": null,
      ""DistributionMarginAmount"": null,
      ""SellingAllowance"": null,
      ""RedistributionCost"": null,
      ""FMRRate"": 0,
      ""FMRAmount"": 0,
      ""ManufacturerDiscountValue"": null,
      ""DistributionDiscountValue"": 0,
      ""DiscountValue"": 0,
      ""FreePieces"": 0,
      ""GSTRate"": 0,
      ""GSTValue"": 0,
      ""AdvanceTaxRate"": 0,
      ""AdvanceTaxValue"": 0,
      ""FurtherTaxRate"": 0,
      ""FurtherTaxValue"": 0,
      ""MRPRate"": 18,
      ""MRPValue"": 68.644,
      ""ConfectionaryTaxRate"": null,
      ""ConfectionaryTaxValue"": null,
      ""InvoicePriceCase"": 2303.0769,
      ""RetailPriceCase"": 2469.2307,
      ""ConsumerPriceCase"": 2700,
      ""ValueWithoutTax"": 171.4472,
      ""TotalTax"": 68.644,
      ""TotalValueWithTax"": 411.5384,
      ""TOAmount"": 0,
      ""TOPercentage"": 0,
      ""TOPercentageValue"": 0,
      ""NetAmount"": 411.5384,
      ""IsFree"": null,
      ""CreatedOn"": ""2023-07-24T15:59:32"",
      ""CreatedBy"": """",
      ""ModifiedOn"": null,
      ""ModifiedBy"": """",
      ""Attribute1"": null,
      ""Attribute2"": null,
      ""Attribute3"": null,
      ""Attribute4"": null,
      ""Attribute5"": null,
      ""Attribute6"": null,
      ""Attribute7"": null,
      ""ReplacePieces"": null,
      ""SDMargin"": 0,
      ""Product"": null,
      ""SaleInvoicePromotions"": [],
      ""SaleInvoiceDetailWBCs"": []
    }
  ],
  ""SaleInvoiceSettlements"": [],
  ""SaleInvoiceRedeliverTrackings"": [],
  ""SaleInvoiceStockSurveys"": []
}";

            // Serialize the sale invoice object to JSON
            string json = JsonConvert.SerializeObject(jsonString);
            string key = "oPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UGoPkAONh5VkGlFPnTHcVIWg0xmJ3UG/Ibtrhhdo50mM0=";

            string newjson=EncryptionHelper.Encrypt(json, key);
            SaleInvoiceService saleInvoiceService = new SaleInvoiceService();
            string invoiceId = "INV-25621";
            string ipfsHash = "IPFS_HASH";
            var transactionHash=await saleInvoiceService.AddOrUpdateSaleInvoice(invoiceId, newjson);




            //var transactionHash = await _ethereumService.CreateInvoice(id, customerName, amount);
            return Ok(transactionHash);
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetInvoice(string id)
        {
            SaleInvoiceService saleInvoiceService = new SaleInvoiceService();
             var invoice=await saleInvoiceService.GetSaleInvoice(id);


            //var invoice = await _ethereumService.GetInvoice(id);
            return Ok(invoice);
        }
    }
}
